config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'events#index'
  devise_for :users, :controllers => {:registrations => "users/registrations",:sessions => "users/sessions"}

  resources :events, only: [:index, :show] do
  	post 'attend', on: :member
  	post 'unattend',on: :member
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
	belongs_to :user
	belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :attendees
	has_many :users,:through => :attendees

	def discount_fees
		self.fees * (1-5/100.to_f) 
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :attendees
    has_many :events,:through => :attendees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	include EventsHelper
	before_action :set_event,only:[:show,:attend,:unattend]
	before_action :get_attendee,only:[:show,:attend,:unattend]
	

	def index
		@events = Event.order(start_date: :asc)	
	end

	def show;end

	def attend
		fees = (current_user.gender == "Female") ? @event.discount_fees : @event.fees
		current_user.attendees.create(event_id: @event.id,joining_date: Date.today,fee_paid: fees)
	end

	def unattend
		attendee = @event.attendees.where(:user_id=>current_user.id) 
		attendee.destroy_all unless attendee.blank?
	end

	def set_event
		@event = Event.find(params[:id])
	end

	def get_attendee
		@attendee_users = get_attendees_users(@event.id)
	end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :authenticate_user!

  def index
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

	def create
		build_resource(registration_params)

		if resource.save
		  if resource.active_for_authentication?
		    set_flash_message :notice, :signed_up if is_navigational_format?
		    sign_up(resource_name, resource)
		    return render :json => {:success => true, :redirect=> root_url}
		  else
		    set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
		    expire_session_data_after_sign_in!
		    return render :json => {:success => true}
		  end
		else
		  clean_up_passwords resource
		  error_messages = resource.errors.messages.first.join(' ') unless resource.errors.messages.blank?
		  return render :json => {:success => false,:errors=>error_messages}
		end
	end
 
  def sign_up(resource_name, resource)
    sign_in(resource_name, resource)
  end

  def after_sign_up_path_for(resource)
   root_url
  end

  private
  def registration_params
    params.require(:user).permit(:email, :password, :password_confirmation,:name,:gender)
  end


end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
    resource = warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#failure")
    sign_in_and_redirect(resource_name, resource)
  end
 
  def sign_in_and_redirect(resource_or_scope, resource=nil)
    scope = Devise::Mapping.find_scope!(resource_or_scope)
    resource ||= resource_or_scope
    sign_in(scope, resource) unless warden.user(scope) == resource
    return render :json => {:success => true,:redirect=> root_url}
  end

  def failure
    return render :json => {:success => false, :errors => ["Login failed."]}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/events_helper.rb
module EventsHelper
	def get_attendees_users(event_id)
		@attendee_users = Attendee.includes(:user).where(event_id: event_id)
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/_attendee_users.html.erb
<div id="user_list">
	<table class="table">
	  <thead>
	    <tr>
	      <th scope="col"></th>
	      <th scope="col">Name</th>
	      <th scope="col">Gender</th>
	    </tr>
	  </thead>
	  <tbody>
	  	<% if attendee_users.present? %>
		  	<% attendee_users.each_with_index do |attendee,i| %>
			    <tr>
			      <th scope="row"><%= i+1 %></th>
			      <td><%= attendee.user.name %></td>
			      <td><%= attendee.user.gender %></td>
			    </tr>
				<% end %>
			<% end %>
	  </tbody>
	</table>
</div>

app/views/events/_show.html.erb
<% if @event.end_date.to_date > Date.today%>
	<div id = "attendee">
	<% if @event.attendees.where(user_id: current_user.id).present? %>
		<%= link_to "UnAttend", unattend_event_path(@event),remote: true,method: 'post',class: "btn btn-primary" %>
	<% else %>
		<%= link_to "Attend", attend_event_path(@event),remote: true,method: 'post',class: "btn btn-primary" %>
	<% end %>
	</div>
<% end %>

app/views/events/attend.js.erb
$("#attendee").html("<%= escape_javascript(render 'events/show',event: @event,attendee_users: @attendee_users) %>");
$("#user_list").html("<%= escape_javascript(render 'events/attendee_users',attendee_users: @attendee_users) %>");

app/views/events/index.html.erb
<% @events.each do |event| %>
	<div class="event-list">
	<div class="event-name"><%= link_to event.name, event_path(event) %></div>
	<div class="event-date"><%= event.start_date.strftime("%d/%m/%y") %></div>
	</div>
<% end %>

app/views/events/show.html.erb
<%= render partial: "show",locals: {attendee_users: @attendee_users} if current_user %>
<%= render partial: "attendee_users",locals: {attendee_users: @attendee_users} %>

app/views/events/unattend.js.erb
$("#attendee").html("<%=  escape_javascript(render 'events/show',event: @event,attendee_users: @attendee_users) %>");
$("#user_list").html("<%=  escape_javascript(render 'events/attendee_users',attendee_users: @attendee_users) %>");

app/views/home/index.html.erb
<h1>Hello</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventTicketApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  		<%= render partial: "layouts/shared/navbar" %>
  	   <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_login_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="loginModal" role="dialog">
  <div class="modal-dialog">
  
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <%= render partial: "devise/sessions/new" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
    
  </div>
</div>
  

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
    </ul>
    <span class="navbar-text">
      <% if user_signed_in? %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
      <% else %>
        <%= link_to "Login", "#-",'data-toggle'=>"modal", 'data-target'=>"#loginModal",id: "login" %> /
        <%= link_to "SignUp", "#-",'data-toggle'=>"modal", 'data-target'=>"#signupModal",id: "signup" %>
      <% end %>
    </span>
  </div>
</nav>


<%= render partial: "layouts/shared/signup_modal" %>
<%= render partial: "layouts/shared/login_modal" %>

app/views/layouts/shared/_signup_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="signupModal" role="dialog">
  <div class="modal-dialog">
  
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <%= render partial: "devise/registrations/new" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
    
  </div>
</div>
  